name: Tests & Pull request Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  tests-unitaires:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - name: Récupértion du repo
        uses: actions/checkout@v2
      - name: Récupération de Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation des dépendances
        run: npm ci
      - run: npm run build --if present
      - run: npm test
  build-app:
    needs: tests-unitaires
    nuns-on: ubuntu-latest
    steps:
      - name: Récupértion du repo
        uses: actions/checkout@v2
      - name: Récupération de Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
  docker:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du repo
        uses: actions/checkout@v2
      - name: Install QEMU Docker
        uses: docker/setup-qemu-action@v1
      - name: Install BuildX docker
        uses: docker/setup-buildx-action@v1
      - name: Connection à Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build et push mon image docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vnstsn/weather:latest

