name: Workflow unit test & push
on:
  push:
    branches:
      - develop
jobs:
  tests-unitaires:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - name: Récupértion du repo
        uses: actions/checkout@v2
      - name: Récupération de Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation des dépendances
        run: npm i
      - name: Tests unitaires
        run: npm test
      - name: tests coverage
        run: npm run cover


